# Generated by Django 4.0.6 on 2023-09-24 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('lineid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('idnumber', models.CharField(blank=True, max_length=25, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('einvoice', models.CharField(blank=True, max_length=20, null=True)),
                ('GUInumber', models.CharField(blank=True, max_length=20, null=True)),
                ('followdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False, verbose_name='封鎖')),
                ('promotable', models.BooleanField(default=False, verbose_name='promotable')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
