# Generated by Django 4.1.1 on 2023-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hailAndChartered', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartered_order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
