# Generated by Django 4.1.1 on 2023-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hailAndChartered", "0002_chartered_order_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartered_order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
