# Generated by Django 4.0.6 on 2023-09-24 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelbot', '0002_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('o_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('o_status', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('rt_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('rt_name', models.CharField(max_length=255)),
                ('rt_price', models.IntegerField(default=0)),
                ('rt_limit', models.IntegerField(default=2)),
                ('rt_image', models.TextField(blank=True, null=True)),
                ('rt_description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_number', models.TextField()),
                ('t_amount', models.IntegerField(default=0)),
                ('t_method', models.CharField(max_length=50)),
                ('t_date', models.DateTimeField()),
                ('t_status', models.BooleanField(default=False)),
                ('t_invoicetype', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.order')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('r_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('r_key', models.CharField(max_length=100, unique=True)),
                ('r_status', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('r_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.roomtype')),
                ('r_users', models.ManyToManyField(blank=True, to='hotelbot.users')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='o_roomtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.roomtype'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelbot.users'),
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.order')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.room')),
            ],
        ),
    ]
