# Generated by Django 4.0.6 on 2023-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='r_status',
            field=models.CharField(choices=[('free', 'free'), ('booked', 'booked'), ('checked', 'checked')], max_length=10),
        ),
    ]
