# Generated by Django 4.0.6 on 2023-09-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_r_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_status',
            field=models.CharField(choices=[('1', '未付訂'), ('2', '已付訂'), ('3', '全付清'), ('4', '結案'), ('5', '已取消')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=10),
        ),
    ]
