# Generated by Django 4.0.6 on 2023-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('a_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('a_name', models.TextField(blank=True, null=True)),
                ('a_img', models.TextField(blank=True, null=True)),
                ('a_date', models.TextField(blank=True, null=True)),
                ('a_address', models.TextField(blank=True, null=True)),
                ('a_price', models.TextField(blank=True, null=True)),
                ('a_organizer', models.TextField(blank=True, null=True)),
                ('a_url', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('at_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('at_name', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
