# Generated by Django 4.0.6 on 2023-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activities_a_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='a_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='a_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='at_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
