# Generated by Django 3.2.15 on 2023-09-29 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelbot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField(null=True)),
                ('img_url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('duration', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField(null=True)),
                ('service', models.TextField(null=True)),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_canceled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelbot.users')),
            ],
        ),
    ]
